import type { D1Migration } from "@cloudflare/vitest-pool-workers";

// `env` in tests is typed as Cloudflare.Env (generated by `wrangler types`).
// TEST_MIGRATIONS is injected by vitest.config.ts rather than wrangler.jsonc,
// so it has to be declared here.
declare global {
  namespace Cloudflare {
    interface Env {
      TEST_MIGRATIONS: D1Migration[];
    }
  }
}

export {};
